---
kind: pipeline
type: docker
name: test

steps:
- name: go tests
  image: golang:alpine
  commands:
  - go build -o cmd-exporter

  - go install golang.org/x/tools/cmd/goimports@latest
  - go install golang.org/x/lint/golint@latest
  - test -z "$(gofmt -l . | tee /dev/stderr)"
  - test -z "$(goimports -local -e -d . | tee /dev/stderr)"
  - golint ./...

---
kind: pipeline
type: docker
name: alpine

depends_on:
- test

steps:
- name: docker build
  pull: always
  image: spritsail/docker-build

- name: docker publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: frebib/cmd-exporter
    tags:
    - latest
    - alpine
    - '%label org.label-schema.version'
    login: {from_secret: docker_login}
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
type: docker
name: debian

depends_on:
- test

steps:
- name: docker build
  pull: always
  image: spritsail/docker-build
  settings:
    dockerfile: Dockerfile.debian

- name: docker publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: frebib/cmd-exporter
    tags:
    - debian
    - '%label org.label-schema.version | %prefix debian'
    login: {from_secret: docker_login}
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: update-readme

steps:
- name: dockerhub-readme
  pull: always
  image: jlesage/drone-push-readme
  settings:
    username: {from_secret: docker_username}
    password: {from_secret: docker_password}
    repo: frebib/cmd-exporter
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 8090cb7290aa2493ec8938979a505ef59f43ba5ac78e09a6c65d94ec2ec86cee

...
